In [3]:
import numpy as np

arr1=np.array([1,2,3,4])
print(arr1)
print(arr1.shape) ##whenever there is single dimentions then there will be only one number

[1 2 3 4]
(4,)


In [21]:
arr2=np.array([1,2,3,4,5])
# print(arr2)
arr2.reshape(1,5) # now it became a two dimensional ->one row 5 columns
# print(arr2.shape)

array([[1, 2, 3, 4, 5]])

In [20]:
arr3=np.array([[1,2,3,4,5],[6,3,4,5,6]])
print(arr3) # one row 3 coulumns
print(arr3.shape) # one row 3 coulumns

[[1 2 3 4 5]
 [6 3 4 5 6]]
(2, 5)


In [26]:
np.arange(0,20,2).reshape(10,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

In [ ]:
np.ones((2,4)) #2 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
## attributes of numy
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.size)
print(arr.ndim) # dimensions
print(arr.itemsize) #gives size in bytes
print(arr.shape)
print(arr.dtype)

8
2
8
(2, 4)
int64


In [ ]:
#universal functions
print(np.sqrt(arr))
# exponential
print(np.exp(arr))
# sine
print(np.sin(arr))
#log
print(np.log(arr))


[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]]
[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825]]
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]]


### array slicing and Idexing

In [49]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('array:\n',arr)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
arr[0][0]

np.int64(1)

In [52]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [57]:
arr[0:,0:2]
# arr[0:3,0:2] both are same

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [58]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [59]:
arr[1:2,1:4]

array([[6, 7, 8]])

In [60]:
# arr[0][0] is eqaul to arr[0,0]
arr[1:]=100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
np.mean(arr)
np.median(arr)
np.std(arr) # standard deviation
np.var(arr) # variancae

np.float64(45.96647328941678)

In [67]:
# logical operations
data=np.array([1,2,3,4,5,6,7,8,9]) 
# data>4
print(data[data>4])
print(data[(data>2)& (data<6)])

[5 6 7 8 9]
[3 4 5]
