In [2]:
print('hello')

hello


In [3]:
import numpy as np

# Create a 2D NumPy array using np.ones
array = np.ones((3, 3), dtype=np.int32)

# Display the array
print("Array:")
print(array)

# 1. itemsize
# Returns the size (in bytes) of each element in the array.
print("\nItemsize (size of each element in bytes):", array.itemsize)

# 2. dtype
# Returns the data type of the elements in the array.
print("Dtype (data type of the elements):", array.dtype)

# 3. ndim
# Returns the number of dimensions of the array.
print("Ndim (number of dimensions):", array.ndim)

# 4. shape
# Returns the shape (size along each dimension) of the array.
print("Shape (size of the array):", array.shape)

# 5. size
# Returns the total number of elements in the array.
print("Size (total number of elements):", array.size)


Array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Itemsize (size of each element in bytes): 4
Dtype (data type of the elements): int32
Ndim (number of dimensions): 2
Shape (size of the array): (3, 3)
Size (total number of elements): 9


In [14]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr=np.empty((3,3,3))
arr

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [7.56595733e-307, 7.56587584e-307, 1.37961302e-306],
        [1.05699242e-307, 8.01097889e-307, 1.78020169e-306]],

       [[7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
        [2.22522597e-306, 1.24611674e-306, 1.29061821e-306],
        [6.23057349e-307, 2.22522597e-306, 1.06810268e-306]],

       [[6.23052935e-307, 2.22522053e-306, 1.11261095e-306],
        [8.45559303e-307, 1.06811422e-306, 1.05694828e-307],
        [1.42410974e-306, 8.34402698e-308, 3.91792476e-317]]])

In [12]:
arr1=np.eye(3)  # is used for placing only ones in diagonal values
print(arr1) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
print(np.full((3,5),2))

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [20]:
np.random.seed(0)

In [21]:
x1=np.random.randint(10,size=6)

In [22]:
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])

np.concatenate([a,b,a,a])



array([1, 2, 3, 2, 3, 4, 1, 2, 3, 1, 2, 3])

In [6]:
grid=np.array([[1,2,3],[2,4,5]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [2, 4, 5],
       [1, 2, 3],
       [2, 4, 5]])

In [7]:
grid=np.array([[1,2,3],[2,4,5]])
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [2, 4, 5, 2, 4, 5]])

In [17]:
a=np.array([[1,2,3],[11,22,33]])
b=np.array([[4,5,6],[44,55,66]])
np.stack((a,b),axis=1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [11]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])